### ISSUE TITLE
Python-psutil is also needed in order to compile

### ISSUE THREAD

**Issue by jchayan** [Gasparen/Dota2TranslatorLinux#1]
Add that to the readme file. I would like to help you out with this, though

**Comment by Gasparen** [comment]
Thanks for pointing this out :)
If you know anything about OpenGL and how the injections of messages should be done that'd be awesome

**Comment by jchayan** [comment]
I've figured out that there's a python binding of the ptrace library (python-ptrace). Which can be used to do the injection, and this translator program would work even for Mac, (dota_linux / dota_osx binaries)
